version: "3"

services:
  ipdog_svelte:
    container_name: ipdog_svelte
    # The name of the image that will be created when building this container
    image: ipdog_svelte_frontend
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Prague
    # Points to a file with the sensitive environment variables
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
  nginx:
    image: nginx:alpine
    container_name: nginx-svelte-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/certs:/etc/nginx/certs
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - ipdog_svelte